### ISSUE TITLE
Add System description to system carousel

### ISSUE THREAD

**Issue by dbasinge** [Weestuarty/diamond-es-de#1]
I would like to have the system description metadata added to the system carousel, under system year.

**Comment by dbasinge** [comment]
I have added the following to theme.xml between sysrel2 and gamecount, which adds the system description metadata, but only goes half across the screen.

 ```
       <text name="sysdespr">
            <pos>0.025 0.160</pos>
            <origin>0 0</origin>
            <size>0.5 0.06</size>
            <text>${systemDescription}</text>
            <fontPath>${sysFont1}</fontPath>
            <fontSize>0.025</fontSize>
            <horizontalAlignment>left</horizontalAlignment>
            <color>${fontColor}</color>
            <zIndex>14</zIndex>
        </text>
        <text name="sysdespr2">
            <pos>0.025 0.160</pos>
            <origin>0 0</origin>
            <size>0.5 0.06</size>
            <text>${systemDescription}</text>
            <fontPath>${sysFont2}</fontPath>
            <fontSize>0.025</fontSize>
            <horizontalAlignment>left</horizontalAlignment>
            <color>000000</color>
            <zIndex>15</zIndex>
        </text>

```

**Comment by Weestuarty** [comment]
Unfortunately this theme doesn't have a variant for the description on the system page. As you seem to know you can edit this yourself, adding the description. The problem in your example is the size you've set. If you need assistance please contact through the discord support channel where I will be happy to help.
