### ISSUE TITLE
Feature Request! - Video Playback on the "Grid" Options

### ISSUE THREAD

**Issue by DaddyItsSticky** [Weestuarty/diamond-es-de#2]
Hello! 

Sorry for coming at you like this, but I have no idea where to begin with modifying your theme for myself.. so here I am.

After about 3-4 hours of bumming around with the different themes and tailoring their limited options to suit my needs, I have concluded that this here, this is the best by far.

However, I'm striving to make this as close to my 'carbon based theme' I use on RetroBat! 
Yours is not far off from this one, however, on the 'system' and 'game' selection screens, with the "grid gamelist" theme option selected, it allows for playing/previewing the scraped video when the game/system's grid is highlighted.
I would absolutely love for this feature to be implemented. I see that your other 'gamelist options' have video playback, so I hoped the same for the grid wouldn't be unachievable. 

- I have included a video of the other theme for reference.

Thank you very much in advance for your time.

https://user-images.githubusercontent.com/130208520/236610170-41ff1157-3057-4ff6-ba32-26ba6ef80baa.mp4

**Comment by Weestuarty** [comment]
No worries, the original plan was to wait until the theme engine updates to add videos inside the grid itself. that said i have added a grid and video view. 
![image](https://user-images.githubusercontent.com/93288988/236622680-57444614-025d-4f78-9201-3286ef57ebcf.png)

**Comment by DaddyItsSticky** [comment]
Mate, this is good shit. You've gone above and beyond and I can't thank you enough already. Really snappy work there too.  Cheers

**Comment by 0x90shell** [comment]
I'm also loving this theme you've made since it's the closest to retrobat/batocera. Has the ESDE dev said video placement options are on the road map for the theme engine?
