### ISSUE TITLE
Theme font size option 

### ISSUE THREAD

**Issue by feeltheburn** [Weestuarty/diamond-es-de#3]
Would love the ability to make the text on game text lists larger.  In a phone on Android,  the text is way too small, and hard to read with contrast to the background.  Using classy color scheme though contrast was an issue on other colors as well.  A size upgrade could fix that. 

Theme is great,  it's just that one thing that makes it hard to use.

**Comment by feeltheburn** [comment]
I altered the "color w/ Text Gamelist" in theme.xml myself for a larger style.

I changed the font sizes as so: 
gamelist: 0.03 to 0.04
description: 0.0225 to 0.035
publisher: 0.03 to 0.04
developer: 0.0225 to 0.04

I'd suggest this as a starting point for a larger font option. This made everything legible on a small screen without being "too" big.

**Comment by Weestuarty** [comment]
The fontSize option was literally just introduced in 3.0.0 release a few weeks ago. Support is being added for older themes its just taking a bit longer than expected to get around to each one due to the android situation. Ill put Diamond at the top of the list though and hopefully will have an update soon for it.

**Comment by feeltheburn** [comment]
Well, I already have mine fixed so no rush. ;-) I'm only a few days into ES usage since I learned of the Android version to put on my RP3+.

**Comment by Weestuarty** [comment]
Hope you are enjoying it and thanks for the support

**Comment by Weestuarty** [comment]
Font Size Support Added

**Comment by feeltheburn** [comment]
Works great, thx!

**Comment by Weestuarty** [comment]
glad to help
